const data = [
  {
    id: 1,
    Channel: 'Manual',
    Subject: 'Agent Call Ticket',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Low',
    Status: 'Open',
    Department: 'QA',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 2,
    Channel: 'Call',
    Subject: 'Agent Call Ticket2',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'Pending',
    Department: 'Java dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 3,
    Channel: 'Facebook',
    Subject: 'Agent Call Ticket3',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Hight',
    Status: 'Resolved',
    Department: 'Intalk dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 4,
    Channel: 'Call',
    Subject: 'Agent Call Ticket4',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'closed',
    Department: 'React dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 5,
    Channel: 'Manual',
    Subject: 'Agent Call Ticket',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Low',
    Status: 'Open',
    Department: 'QA',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 6,
    Channel: 'Call',
    Subject: 'Agent Call Ticket2',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'Pending',
    Department: 'Java dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 7,
    Channel: 'Facebook',
    Subject: 'Agent Call Ticket3',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Hight',
    Status: 'Resolved',
    Department: 'Intalk dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 8,
    Channel: 'Call',
    Subject: 'Agent Call Ticket4',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'closed',
    Department: 'React dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 9,
    Channel: 'Manual',
    Subject: 'Agent Call Ticket',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Low',
    Status: 'Open',
    Department: 'QA',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 10,
    Channel: 'Call',
    Subject: 'Agent Call Ticket2',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'Pending',
    Department: 'Java dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 11,
    Channel: 'Facebook',
    Subject: 'Agent Call Ticket3',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Hight',
    Status: 'Resolved',
    Department: 'Intalk dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 12,
    Channel: 'Call',
    Subject: 'Agent Call Ticket4',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'closed',
    Department: 'React dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 13,
    Channel: 'Manual',
    Subject: 'Agent Call Ticket',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Low',
    Status: 'Open',
    Department: 'QA',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 14,
    Channel: 'Call',
    Subject: 'Agent Call Ticket2',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'Pending',
    Department: 'Java dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 15,
    Channel: 'Facebook',
    Subject: 'Agent Call Ticket3',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Hight',
    Status: 'Resolved',
    Department: 'Intalk dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  },
  {
    id: 16,
    Channel: 'Call',
    Subject: 'Agent Call Ticket4',
    RequestType: 'Enquiry',
    IssueType: 'Enquiry',
    Priority: 'Medium',
    Status: 'closed',
    Department: 'React dev',
    Customer: 'Mustafa',
    CreatedDate: '06/04/2024',
    DueDate: '07/04/2024'
  }
]

const FILTERS = [
  { id: 1, label: 'Agent', options: ['Mustafa Dahodwala', 'Parth Patel', 'Aadil', 'Nimit'], type: 'select' },
  { id: 2, label: 'Product', options: ['Helpinbox', 'Intalk', 'ChatinBox', 'Aniceya'], type: 'select' },
  { id: 4, label: 'Channel', options: ['Email', 'Manual', 'Facebook', 'Twitter'], type: 'select' },
  { id: 5, label: 'Status', options: ['Open', 'Pending', 'Close', 'Resolved'], type: 'select' },
  { id: 7, label: 'Department', options: ['Support', 'DevOps', 'Devlopment', 'Testing'], type: 'select' },
  { id: 8, label: 'Issue Type', options: ['Incident', 'Problem', 'Task', 'Dev'], type: 'select' },
  {
    id: 9,
    label: 'Date Range Filter',
    options: ['filter3-option1', 'filter3-option2', 'filter3-option3', 'filter3-option4'],
    type: 'date'
  }
]

export { FILTERS, data }
